### ISSUE TITLE
stinit.def example for LTO-6 

### ISSUE THREAD

**Issue by jonasstein** [iustin/mt-st#10]
#7  provides an example configuration for LTO3, but how should the entry look like for LTO6? 
I have a LTO6 drive available, so please let me know, how I can help.

the status output while an LTO-5 tape is loaded is:

```
mt -f /dev/st0 status
SCSI 2 tape drive:
File number=0, block number=0, partition=0.
Tape block size 0 bytes. Density code 0x58 (LTO-5).
Soft error count since last status=0
General status bits on (41010000):
 BOT ONLINE IM_REP_EN
```

**Comment by iustin** [comment]
Not sure if anything is needed, actually. I also have an LTO6, and it works with the default config…

**Comment by jonasstein** [comment]
thank you very much. I thought I could have a wrong configuration, because my tape breaks often. I saw with mbuffer, that the buffer is still full, but I could hear the LTO-5 tape stop every 18 GB. LTO-5 has 80 wraps for 1.5 TB which would be in the same order, however the support told me, that I should not hear a stop noise and that the tape would not wind. Thank you for the great mt tool.
