### ISSUE TITLE
Update maintainer information

### ISSUE THREAD

**Issue by dsommers** [iustin/mt-st#2]
Currently the maintainer information found in mt-st-1.1.lsm and mt.c points at Kai Makisara.  I was in contact with him and got pointed into this direction.  I believe it would be good if the maintainer info got updated.

As a side note, an announcement somewhere (like the README?) that you have taken over the maintenance of this package would probably also not be a bad thing.

**Comment by iustin** [comment]
Thanks for the reminder. Yes, I indented to do that, however some real life changes put a temporary stop to all my opensource work; will try to do this soon.

**Comment by iustin** [comment]
Thanks to your pull request, I also realised I had a number of unpushed changes (small things) laying around on my machine; will try to cleanup and make a small release soon.

**Comment by iustin** [comment]
I just published the 1.2 release, including the note about changed maintainership. Thanks!
